// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzktupxmrdmxxeaqbqmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6a3R1cHhtcmRteHhlYXFicW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDkyNzEsImV4cCI6MjA1OTkyNTI3MX0.nRzCTCdv8DobjOuiJEdPaBMZVtKqaGpYQ1e_IqSnotk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);